"use client"
import { Inter } from "next/font/google";
import "./index.css";
import { ParallaxProvider } from "react-scroll-parallax";
import { useEffect } from "react";
// import NoCaptcha from "no-captchaaa";
const inter = Inter({ subsets: ["latin"] });
import dynamic from 'next/dynamic';
const NoCaptcha = dynamic(() => import('no-captchaaa'), { ssr: false });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  useEffect(() => {
    (
      async () => {
        const { default: LocomotiveScroll } = await import("locomotive-scroll");
        const locomotiveScroll = new LocomotiveScroll();
      }
    )()
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ParallaxProvider>
          {/* <NoCaptcha app={children} /> */}
{children}
        </ParallaxProvider>
      </body>
    </html>
  );
}
